# Dependabot configuration for Personal Website
# Conservative approach based on Tailwind CSS v4 beta lessons learned

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    
    # Conservative approach: ignore major/minor updates for critical dependencies
    ignore:
      # React ecosystem - critical for personal website
      - dependency-name: "react"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      
      # Tailwind CSS - NEVER auto-update to v4 beta again!
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
      
      # Next.js - test major updates manually
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      
      # TypeScript - major updates can break compatibility
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    
    # Personal website specific groupings
    groups:
      # Group blog-related updates
      blog-functionality:
        patterns:
          - "*notion*"
          - "@notionhq/*"
      
      # Group contact form updates
      contact-form:
        patterns:
          - "resend"
          - "*mail*"
      
      # Group theme/UI updates
      ui-theming:
        patterns:
          - "next-themes"
          - "*theme*"
    
    labels:
      - "dependencies"
      - "personal-website"
    
    reviewers:
      - "mhmcdermott"
    
    open-pull-requests-limit: 3
    
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Enable security updates - higher priority
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "security"
    labels:
      - "security"
      - "personal-website"
      - "automated"
    
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "automated"